### ISSUE TITLE
dbms_utility.compile_schema needs an upper case schema name

### ISSUE THREAD

**Issue by hhudson** [OraOpenSource/apex-sert#10]
Hi,

### Issue: 
In the ins.sql file in https://github.com/OraOpenSource/apex-sert/blob/master/releases/sert_050100.zip, on line 454, there exists the following code:
```
dbms_utility.compile_schema(schema => 'sv_sert_050100');
```
This causes an error when I run it because dbms_utility.compile_schema is case sensitive (https://asktom.oracle.com/pls/asktom/f?p=100:11:::::P11_QUESTION_ID:1418403973266).

### Resolution: 
I changed line 454 in ins.sql (sert_050100.zip) to the following:
```
dbms_utility.compile_schema(schema => 'SV_SERT_050100');
```
Uppercasing the schema name fixes my problem.

Thanks,
Hayden

**Comment by DougAGault** [comment]
Actually this is built as part of the ANT build process and uses a replacement variable for the version number, but the 'sv_sert' is hardcoded in lower case. 

We should probably change all places where 'sv_sert' is mentioned to be 'SV_SERT' instead.

**Comment by sspendol** [comment]
Changed line 454 to use uppercase SV_SERT.  The other places that "sv_sert_" is used are outside of quotes, so there should be no issues.
