### ISSUE TITLE
@SV_VERSION@

### ISSUE THREAD

**Issue by mongolu** [OraOpenSource/apex-sert#11]
Hello.
I tried to install it and bumped into wall with "@SV_VERSION@" part of strings used in installation files.
Did I do something wrong?
Or it is supposed I should make a replacement in all installation files with some string, before running ins.sql?

Oracle 11.2.0.4, APEX 18.1 and executed ins.sql from windows cmd.
```
...
create user sv_sert_@SV_VERSION@ identified by "x" default tablespace "APEX_SERT" quota unlimited on "APEX_SERT" temporary tablespace "TEMP"
                    *
ERROR at line 1:
ORA-00922: missing or invalid option
...
```

And all subsequent statements failed.

Thanks.

**Comment by mongolu** [comment]
> Hello.
> I tried to install it and bumped into wall with "@SV_VERSION@" part of strings used in installation files.
> Did I do something wrong?
> Or it is supposed I should make a replacement in all installation files with some string, before running ins.sql?
> Thanks.

Oracle 11.2.0.4, APEX 18.1 and executed ins.sql from windows cmd.

**Comment by sspendol** [comment]
You should download APEX-SERT from here: https://github.com/OraOpenSource/apex-sert/tree/master/releases

Having said that, we're still working on a release for 18.1 - currently, 5.1 is the most current release.

Thanks,

- Scott -
