### ISSUE TITLE
APEX 5.0 / ORDS 18 compatibility?

### ISSUE THREAD

**Issue by MonkeyThink** [OraOpenSource/apex-sert#12]
We're trying to run APEX-SERT on APEX 5.0.  It was previously working, and we've now updated from using ORDS on Glassfish to ORDS 18 in standalone mode.

Now we get a 403 error from ORDS with the message 'Access to the procedure named: sv_sert_apex.launch_sert is denied.'

Are there any known issues here?

**Comment by sspendol** [comment]
Have a look at the installer for APEX-SERT 5.1 - it will create a web service that is called vs. the PL/SQL procedure.  If you replicate this approach, it should work.

Thanks,

- Scott -

**Comment by kistler** [comment]
Trying to locate the web service call as described in the previous post, but find nothing in the installation logs that show sv_sert_apex.launch_sert. Can you tell me what exactly I'm looking for?

Or should I reinstall SERT now that I've upgraded APEX and ORDS to 18?

**Comment by MonkeyThink** [comment]
I've checked the SV_SERT_APEX schema and the launch_sert procedure exists, and EXECUTE privilege is granted to APEX_PUBLIC_USER.

Haven't figured out why I'm getting the original error message.

**Comment by MonkeyThink** [comment]
I have fixed it! 😊

I have installed the webservice using scripts from the 5.1 version of APEX-SERT and am using the webservice to launch the SERT app.

Because I was executing the steps through a GUI tool to the database (TOAD) and not directly on the OS using SQL*Plus I extracted the necessary bits of the install files to run, rather than just executing the files, but I've given the names of the files I used below for anyone who want/needs to replicate this.

The exact steps I took are:

- Download and extract apex-sert-5.1.02.zip
- Log in as APEX_05000 user (could use SYS but DBA's haven't given me that password!).

- Run the following extracted from source\app\_install_ws.sql:

PROMPT  =============================================================================
PROMPT  == Web Service File Start
PROMPT  =============================================================================
PROMPT

-- Check if the application ID already exists for SERT
DECLARE
  l_workspace     varchar2(20) := 'SERT';
  l_workspace_id  number;
  l_app_id_check  NUMBER;
BEGIN

-- Get the Workspace Name ID value
SELECT workspace_id
  INTO l_workspace_id
  FROM apex_workspaces
  WHERE workspace = l_workspace;
  
-- Workspace Security
apex_application_install.set_workspace_id( l_workspace_id );
apex_application_install.generate_offset;
  
EXCEPTION WHEN NO_DATA_FOUND then
    dbms_output.put_line('ISSUE: The workspace SERT does not exist at this time.');
    raise VALUE_ERROR;
END;

- Execute “source\app\apex-sert_launcher.sql”

Followed by: exec APEX_APPLICATION_INSTALL.CLEAR_ALL;

Change the launch link to the version that’s in the 5.1 install output( In “source\ins.sql”):

<a href="javascript:var launchSERT=window.open('sert/launch/' + $v('pInstance'));"><span class="a-Icon icon-run-page"></span>&nbsp;Launch APEX-SERT</a>

Hey presto - It works.
