### ISSUE TITLE
Session state protection violation with Apex 18

### ISSUE THREAD

**Issue by PetrShchukin** [OraOpenSource/apex-sert#13]
Hi, I was wondering are you still working on compatibility with Apex 18? Here we have an issue with logging. There is 'Your session has expired. Please login to your APEX Workspace again and re-launch APEX-SERT. ' And if I go on SERT from Apex there is an error "Session state protection violation: This may be caused by manual alteration of a URL containing a checksum or by using a link with an incorrect or missing checksum. If you are unsure what caused this error, please contact the application administrator for assistance." Thanks!

**Comment by sspendol** [comment]
Petr,

I have not thoroughly tested APEX-SERT on 18 yet.  I have heard of people who have gotten it to work, however.  We do plan on releasing a new version; just not 100% sure of the date at this point.

Thanks,

- Scott -

**Comment by MonkeyThink** [comment]
PetrShchukin, please do keep us updated if you find out how to get this working. I'm likely to be migrating to APEX 18 (if not 19) sometime in the next few months (or at least trying it out).  Likewise if we get it working on APEX 18 I'll let you know how.

**Comment by stephenjfbrennan** [comment]
Hi
I found and resolved 3 installation issues on Apex 18.2.x, see below, and have apex-sert working now. Still some testing to do :-)

------------------------------ 
### **Issue 1 - User Grants**

Listing all available tablespaces...


Tablespace Name                                                                                                             
APEX                                                                            
LOB_DATA                                                                        
QUERCUS_DATA                                                                    
QUERCUS_IDX                                                                     
SYSAUX                                                                          
SYSTEM                                                                          
TEMP                                                                            
UNDOTBS1                                                                        
USERS                                                                           

Please enter the default tablespace to be used for SV_SERT_050102 [USERS] : APEX
Please enter the temporary tablespace to be used for SV_SERT_050102 [TEMP] : 

User created.


Grant succeeded.

DECLARE
*
ERROR at line 1:
ORA-00903: invalid table name 
ORA-06512: at line 12 `

**Resolution:**

Change line in file /ins/user_grants.sql
_FOR x IN (SELECT MAX(username) username FROM all_users WHERE username LIKE 'APEX_0%')_
to
_FOR x IN (SELECT MAX(username) username FROM all_users WHERE username LIKE 'APEX_1%')_

------------------------------ 
### **Issue 2 - Views**
`== SV_SEC_COL_SET_UI_DT_SET_V
== SV_SEC_COL_SET_UI_MOB_SET_V
== SV_SEC_EXCEPTIONS_V
== SV_SEC_APEX_SESSIONS_V
DECLARE
*
ERROR at line 1:
ORA-00903: invalid table name 
ORA-06512: at line 19 


== SVV_DBA_ROLE_PRIVS
== SVV_DBA_SYS_PRIVS
== SVV_DBA_TAB_PRIVS`

**Resolution**
Change line in /vw/sv_sec_apex_session_v.sql
_FOR x IN (SELECT MAX(username) username FROM all_users WHERE username LIKE 'APEX_0%')_
to
_FOR x IN (SELECT MAX(username) username FROM all_users WHERE username LIKE 'APEX_1%')_

------------------------------ 
### **Issue 3 - Configuration**
`== SV_SEC_COLORS
== SV_SEC_HTP_PROCS
== SV_SEC_SNIPPETS
  SELECT 'INSTANCE_ID', value, 'N' FROM apex_050100.wwv_flow_platform_prefs WHERE name = 'INSTANCE_ID'
                                                    *
ERROR at line 2:
ORA-00942: table or view does not exist 


== INSERTING into SV_FWK_CSS_DATA`

**Resolution**
Change line in /cfg/sv_sec_snippets.sql

_INSERT INTO sv_sec_snippets (snippet_key, snippet, editable)
SELECT 'INSTANCE_ID', value, 'N' FROM apex_050100.wwv_flow_platform_prefs WHERE name = 'INSTANCE_ID'
/_

to

_INSERT INTO sv_sec_snippets (snippet_key, snippet, editable)
SELECT 'INSTANCE_ID', value, 'N' FROM apex_180200.wwv_flow_platform_prefs WHERE name = 'INSTANCE_ID'
/_

**Comment by sspendol** [comment]
@stephenjfbrennan thanks for the post.  I'll add these changes to the list when we get to upgrading APEX-SERT.

- Scott -

**Comment by TonyCMiller** [comment]
Just asking, will this be for 19.x or 18.x version of Apex?

**Comment by sspendol** [comment]
Tony,

Hoping to get one out for 18.1 or maybe 18.2 (they are very similar) and 19.1 at some point.

- Scott -

**Comment by TonyCMiller** [comment]
Great news.. we are in a holding pattern on security testing software..
tried apexsec and was far from impressed..

Now just hoping we can get things going with apexsert and aop ( don't get
me started.. politics galore over a print engine???)

Now attending 2 day class on Scrum...
