### ISSUE TITLE
APXWS_HL_EXPR_VAL3_3 error

### ISSUE THREAD

**Issue by unficyp** [OraOpenSource/apex-sert#14]
Hi,
running APEX Sert 050102 on 12cR2 and APEX 19.1.
Most of the APP is working, except some sites in Home / Evaluations / etc , e.g. Page Alias SV_XSS_HIDDEN_ITEMS gives the following error:

> Unable to bind "APXWS_HL_EXPR_VAL3_3". Use double quotes for multi byte items or verify length of item is 30 bytes or less. Use v() syntax to reference items longer than 30 bytes.
> 
> Contact your application administrator.

Looking at the Debug Messages for the session, i see:

> - component: APEX_APPLICATION_PAGE_REGIONS Hidden Items (609050028107032777)
> - error_backtrace: ORA-06512: at "SYS.DBMS_SQL", line 1427
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 858
> 
> - ora_sqlerrm: ORA-01006: bind variable does not exist
> ORA-06512: at "SYS.DBMS_SQL", line 1427
> - ora_sqlcode: -1006
> - apex_error_code: WWV_DBMS_SQL.UNABLE_TO_BIND_ERR
> - is_internal_error: true
> - display_location: ON_ERROR_PAGE
> - additional_info: Contact your application administrator.
> Error: Unable to bind "APXWS_HL_EXPR_VAL3_3". Use double quotes for multi byte items or verify length of item is 30 bytes or less. Use v() syntax to reference items longer than 30 bytes.
> SID=23
> USER=APEX_PUBLIC_USER
> INSTANCE=1
> 
> GET https://apexdev/ords/dev
> REMOTE_ADDR=192.168.20.230
> REMOTE_USER=APEX_PUBLIC_USER
> APEX_LISTENER_VERSION=19.1.0.r0921545
> REFERER=https://apexdev/ords/dev/f?p=9002:500:6342170987994::NO:::
> HTTP_COOKIE=_ga=GA1.2.881281428.1550047378
> 
> CGI: PATH_INFO = /f?p=9002:SV_XSS_HIDDEN_ITEMS:6342170987994:::RP::&cs=3THt0_eXmbEV16VASQvAcehpF0wodfyzN-oiW7o9JA3N-emlJfF6YQmhY9DQHLt5hgePK7nHcP2isio33Tyv5TA
> 

What could be the reason for this ?

Thanks in advance

**Comment by sspendol** [comment]
Not sure what the issue is, as the item "APXWS_HL_EXPR_VAL3_3" is not part of SERT.

Furthermore, APEX-SERT should not be used on APEX 18.1+, as it has not yet been modified to work with the new features.  Please understand that it may produce erroneous results in that configuration.

- Scott -

**Comment by rajeshvig** [comment]
The issue was caused on certain pages (mostly in XSS and URL section of report) with query column named result. Simply using alias to those column fixes the issue. I was able to fix this issue in apex 19.1 pull request rajeshvig:19.1 submitted for the same. mostly the  fix should also work on 18.2.
