### ISSUE TITLE
apex-sert menu links

### ISSUE THREAD

**Issue by silviavali** [OraOpenSource/apex-sert#3]
When launching the apex-sert and report is created, then if you are on any of the pages belonging to the Dashboard (Issues by Category, Issues by Severity etc...) and want to choose any other page under Dashboard from the main menu (Issues by Category, Issues by Severity etc...), then the links from the main menu under Dashboard do not work ( from the tab menu under Dashboard links work). 

Currently using APEX v. 4.2.0

**Comment by sspendol** [comment]
silviavali,

Can you reproduce this issue on APEX 4.2.6?

Thanks,
- Scott -

**Comment by silviavali** [comment]
My applications that I ran it currently on are in 4.2.6.00.03 and yes it has the same failure in same place.

**Comment by silviavali** [comment]
I have tried to find a formal way of contacting you on a specific matter, could you contact me on my CERN e-mail found here : https://phonebook.cern.ch/phonebook/#personDetails/?id=803457

**Comment by silviavali** [comment]
Would you be kind and contact me formally on a specific matter at Silvia.Vali@cern.ch https://phonebook.cern.ch/phonebook/#personDetails/?id=803457
