### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by deepajrao** [OraOpenSource/apex-sert#4]
Hello Scott,

Is there a User Guide for the application ? the documents link does not include it
https://github.com/OraOpenSource/apex-sert/tree/269352e68ec93b4ee1f8a72ad651f4ffd1fc9f07/doc

Thanks,
Deepa

**Comment by sspendol** [comment]
The 4.2 Users Guide can be found here: https://github.com/OraOpenSource/apex-sert/tree/sert4/source/doc

Still need to finish and upload the one for 5.0.

Thanks,

Scott

**Comment by deepajrao** [comment]
Thanks Scott.
