### ISSUE TITLE
Wrongly identified Defects

### ISSUE THREAD

**Issue by tmilowski** [OraOpenSource/apex-sert#7]
Running the Sert 5.0 against the Apex 5.0.3
I noticed the following wrongly identified errors (in my opinion):
*Page Authentication: The login page is flagged even though it is defined as "Public Page"
*Page Access Protection: The items on public login page are flagged
*Enable Legacy Authentication Attributes: I believe this does not exists in Apex 5.0 and up
*Post-Logout URL: it Fails but it is set to the "Home Page" so it shouldn't

**Comment by sspendol** [comment]
*Page Authentication: The login page is flagged even though it is defined as "Public Page"
I'd prefer to leave this alone.  It's easy to create an exception, and my fear is that it would be hard to come up with fool-proof logic for what constitutes a "login page".

*Page Access Protection: The items on public login page are flagged
Same thoughts as above.  

*Enable Legacy Authentication Attributes: I believe this does not exists in Apex 5.0 and up
Just checked; it is still there in 5.0.

*Post-Logout URL: it Fails but it is set to the "Home Page" so it shouldn't
This one needs to be fixed, as it's no longer where the Post-Logout URL resides.

Thanks for the feedback!

- Scott -
