### ISSUE TITLE
sert_050100b3 missing sv_sert_apex.launch_sert stored procedure

### ISSUE THREAD

**Issue by dpaske** [OraOpenSource/apex-sert#8]
I installed sert_050100b3 into an APEX 5.1.4 instance. Copied and pasted the link to APEX-SERT into the System Message in the APEX admin screen. When users clicked on the link, they got an HTTP-404 error. Discovered that the stored procedure "sv_sert_apex.launch_sert" did not exist in the database.  I found the code to create launch_sert in the 5.0 branch. I created the procedure in the sv_sert_apex schema and everything is working.

**Comment by sspendol** [comment]
Dan - let me take a look at this.  It should have created that procedure automatically.

- Scott -

**Comment by sspendol** [comment]
Dan - with SERT 5.1, the default launching mechanism is ORDS, so that procedure is no longer used.  If you do not use ORDS, you can certainly use sv_sert_apex.launch_sert as we did in 5.0.
